---
title: "Projet Visualisation"
author: '[Arnaud Frering, Stéfan Baudier, Thomas Rodriguez](https://github.com/ArnaudFrering)'
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    df_print: paged
    toc: yes
  epuRate::PCTG:
    code_folding: hide
    number_sections: no
    toc: yes
mail: arnaud.frering@mines-ales.org
linkedin: arnaud-frering-b52150161
github: ArnaudFrering
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r ,}
#Chargement des librairies
library(ggplot2) 
library(dplyr)
library(gapminder) 
library(forcats)
```

## Importation des données 

```{r cars} 
#on importe les deux dataframe
data <- read.csv("https://raw.githubusercontent.com/ArnaudFrering/Projet_Visualisation/master/Tableau_Points_Fantasy.csv", header = TRUE, sep = ";")
data2<- read.csv("https://raw.githubusercontent.com/ArnaudFrering/Projet_Visualisation/master/Donnees_boxplot.csv", header = FALSE, sep = ";")


data_boxplot <- as.data.frame(t(data2)) #transposition des lignes en colonnes
data_3 <- as.data.frame(data_boxplot[2:64,c(1,3,8)]) #selection des colonnes Durant Curry et Match sans la 1ere ligne
names(data_3) <- c("Match", "Durant", "Curry") #on renomme les colonnes avec les noms concernés 

#on transforme les facteurs en valeur numérique
data_3$"Durant"<-as.numeric(as.character(data_3$"Durant"))
data_3$"Curry"<-as.numeric(as.character(data_3$"Curry"))
data_3$"Match"<-as.numeric(as.character(data_3$"Match"))

```

##Premiers graphs

```{r ,}
  head(data, 10) %>%
  arrange(Moyenne) %>% #on trie suivant la moyenne
  mutate(Joueur=factor(Joueur, Joueur)) %>% #classement par les joueurs en fonction de leur moyenne
  # Création d'un graphique de la moyenne en fonction du joueur
  ggplot(aes( x=Joueur, y=Moyenne )) +
  #on utilise point et segment pour créer un bubble chart
    geom_point()+
    geom_segment(aes( x=Joueur, y=0,  xend=Joueur, yend = Moyenne ),color = "black")+
    coord_flip()+ #on inverse l'axe des abscisses avec celui des ordonnées
  #on met en valeur 2 joueurs de la même équipe
    annotate(geom = "point", x = "Durant", y = 46.72, shape = 21, color = "blue", size = 5, fill = "yellow")+
    annotate(geom = "point", x = "Curry", y = 40.16, shape = 21, color = "blue", size = 5, fill = "yellow")+
  #on affiche leur moyenne
    annotate(geom = "text", x = "Durant", y = 50, label = "46.72", color = "blue") +
    annotate(geom = "text", x = "Curry", y = 43.5, label = "40.16", color = "blue") 
```

```{r ,}
# basic scatterplot
data_3 %>%
  #on affiche 2 courbes sur un même graphique 
  ggplot(aes(Match, Durant), ylbl ="Performance") +
  geom_line(color = "red")+
  geom_line(aes(Match, Curry), color = "blue")+
  #association de chaque courbe à un joueur en rappelant la moyenne de chacun
  annotate(geom = "text", x = 35, y = 49.72, label = "Durant", color = "red")+
  annotate(geom = "text", x = 35, y = 46.72, label = "av = 46.72", color = "red")+
  annotate(geom = "text", x = 35, y = 43.16, label = "Curry", color = "blue")+
  annotate(geom = "text", x = 35, y = 40.16, label = "av = 40.16", color = "blue")+
  ylab("Performance")
  
```

```{r ,}

